### ISSUE TITLE
No spotify info displayed

### ISSUE THREAD

**Issue by oscardurst** [Saiyato/volumio-hd44780-plugin#9]
@Saiyato thank you for the plugin it is nice! but can you please guide me how to add the info from spotify?  I've been analyzing the  **paralleldisplay.js** file and i see sometihing related to webradio etc, maybe it is just matter of adding some lines to the code in order to display the track information from spotify? 

thanks in advanced
Oscar

**Comment by Saiyato** [comment]
Hi @oscardurst 

This plugin has been discontinued in favor of pydPiper. You don't see Spotify info, because Spotify doesn't use mpd and this plugin only supports showing what happens in MPD. You will need to get your hands dirty and program it yourself, because the libraries used by this plugin don't support anything other than MPD.
